#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

SEED="${1:-hybridchain-20node-seed}"
OUT_ENV="${2:-.env.20nodes}"
OUT_VALIDATOR_FILE="${3:-validator_keys.txt}"

COUNT=20

if [[ ! -f cp.txt ]]; then
  mvn -q -DskipTests dependency:build-classpath -Dmdep.outputFile=cp.txt
fi
mvn -q -DskipTests compile

KEYS_RAW="$(mktemp)"
trap 'rm -f "$KEYS_RAW"' EXIT

java -cp "target/classes:$(cat cp.txt)" com.hybrid.blockchain.tools.KeygenTool "$COUNT" "$SEED" > "$KEYS_RAW"

declare -A PRIV

declare -A PUB

declare -A ADDR

while IFS='=' read -r key value; do
  case "$key" in
    NODE_*_PRIVATE_KEY)
      idx="${key#NODE_}"
      idx="${idx%_PRIVATE_KEY}"
      PRIV["$idx"]="$value"
      ;;
    NODE_*_PUBLIC_KEY)
      idx="${key#NODE_}"
      idx="${idx%_PUBLIC_KEY}"
      PUB["$idx"]="$value"
      ;;
    NODE_*_ADDRESS)
      idx="${key#NODE_}"
      idx="${idx%_ADDRESS}"
      ADDR["$idx"]="$value"
      ;;
  esac
done < "$KEYS_RAW"

for i in $(seq 1 20); do
  if [[ -z "${PRIV[$i]:-}" || -z "${PUB[$i]:-}" || -z "${ADDR[$i]:-}" ]]; then
    echo "Missing key material for index $i" >&2
    exit 1
  fi
done

VALIDATOR_PUBKEYS="${PUB[2]},${PUB[3]},${PUB[4]},${PUB[5]}"

cat > "$OUT_ENV" <<EOF
# Auto-generated by scripts/generate_keys.sh
# Deterministic seed: $SEED
STORAGE_AES_KEY=00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff

NODE_SEED_PRIVATE_KEY=${PRIV[1]}
NODE_VALIDATOR_1_PRIVATE_KEY=${PRIV[2]}
NODE_VALIDATOR_2_PRIVATE_KEY=${PRIV[3]}
NODE_VALIDATOR_3_PRIVATE_KEY=${PRIV[4]}
NODE_VALIDATOR_4_PRIVATE_KEY=${PRIV[5]}

NODE_PEER_1_PRIVATE_KEY=${PRIV[6]}
NODE_PEER_2_PRIVATE_KEY=${PRIV[7]}
NODE_PEER_3_PRIVATE_KEY=${PRIV[8]}
NODE_PEER_4_PRIVATE_KEY=${PRIV[9]}
NODE_PEER_5_PRIVATE_KEY=${PRIV[10]}
NODE_PEER_6_PRIVATE_KEY=${PRIV[11]}
NODE_PEER_7_PRIVATE_KEY=${PRIV[12]}
NODE_PEER_8_PRIVATE_KEY=${PRIV[13]}
NODE_PEER_9_PRIVATE_KEY=${PRIV[14]}
NODE_PEER_10_PRIVATE_KEY=${PRIV[15]}
NODE_PEER_11_PRIVATE_KEY=${PRIV[16]}
NODE_PEER_12_PRIVATE_KEY=${PRIV[17]}
NODE_PEER_13_PRIVATE_KEY=${PRIV[18]}
NODE_PEER_14_PRIVATE_KEY=${PRIV[19]}
NODE_PEER_15_PRIVATE_KEY=${PRIV[20]}

VALIDATOR_PUBKEYS=$VALIDATOR_PUBKEYS
EOF

cat > "$OUT_VALIDATOR_FILE" <<EOF
# Deterministic validator keypairs generated from seed: $SEED
validator-1 private=${PRIV[2]} public=${PUB[2]} address=${ADDR[2]}
validator-2 private=${PRIV[3]} public=${PUB[3]} address=${ADDR[3]}
validator-3 private=${PRIV[4]} public=${PUB[4]} address=${ADDR[4]}
validator-4 private=${PRIV[5]} public=${PUB[5]} address=${ADDR[5]}
EOF

echo "Generated deterministic key material"
echo "- env file: $OUT_ENV"
echo "- validator keys: $OUT_VALIDATOR_FILE"
echo "- validator pubkeys: $VALIDATOR_PUBKEYS"
